************************************************************************
*^ Written By      : Hxy
*^ Date Written    : 2014/08/18
*^ Include Name    : ZSQLEXPLORERO02
*^ Used in Programs: <Programs referencing this include>
*^ Purpose         : To define parameters and varants
*
*^ Other           :
************************************************************************





******************************************************
*&      Module  STATUS_0200  OUTPUT
******************************************************


MODULE status_0200 OUTPUT.

  SET PF-STATUS 'SCREEN200'.
  SET TITLEBAR  ''.

ENDMODULE. " STATUS_0200 OUTPUT